//! Monthly report generation: roll one employee's month up from the data the
//! system already keeps, and freeze it in `monthly_reports`.
//!
//! Sources (all already org-local/IST day-keyed — see `crate::org_time`):
//!   * `attendance_days`   — per-day worked seconds + status (the day series and
//!     the present/partial/absent/leave/holiday/weekend counts)
//!   * `analysis_reports`  — the per-day AI alignment score, rolled up into
//!     "N of M analysed days scored at or above the threshold"
//!   * `time_grants`       — manual grace time, surfaced separately so a month's
//!     total is explainable rather than silently inflated
//!
//! HR/PMs may generate a report for ANY month on demand (including the current,
//! still-running one); the scheduler generates the previous month automatically
//! once it closes. Both paths call [`build`], and the write is an upsert, so a
//! regeneration simply refreshes the row.

use chrono::{Datelike, NaiveDate};
use sqlx::PgPool;
use uuid::Uuid;

use crate::db::monthly_reports::{self, MonthDay, MonthlyReport, MonthlyReportInput};
use crate::db::{analysis_reports, attendance, time_grants};
use crate::error::AppError;

/// A day "counts as aligned" at or above this score. HR reads the monthly report
/// as "N days were above X%", so the threshold is part of the stored row —
/// changing the env later can't silently reinterpret an old report.
const DEFAULT_ALIGNMENT_THRESHOLD: f64 = 50.0;

pub fn alignment_threshold() -> f64 {
    std::env::var("MONTHLY_ALIGNMENT_THRESHOLD")
        .ok()
        .and_then(|s| s.parse().ok())
        .filter(|v: &f64| v.is_finite() && *v >= 0.0 && *v <= 100.0)
        .unwrap_or(DEFAULT_ALIGNMENT_THRESHOLD)
}

/// Normalise any date to the first day of its month (the month key).
pub fn month_key(day: NaiveDate) -> NaiveDate {
    NaiveDate::from_ymd_opt(day.year(), day.month(), 1).expect("valid first-of-month")
}

/// Last day of the month `month` starts.
pub fn month_end(month: NaiveDate) -> NaiveDate {
    let (y, m) = (month.year(), month.month());
    let (ny, nm) = if m == 12 { (y + 1, 1) } else { (y, m + 1) };
    NaiveDate::from_ymd_opt(ny, nm, 1)
        .expect("valid next month")
        .pred_opt()
        .expect("valid last day")
}

/// Build (or rebuild) one employee's report for `month` and store it.
///
/// `generated_by` is the HR/PM who asked for it, or `None` for the month-end
/// scheduler — the UI shows "generated automatically" vs "generated by X".
pub async fn build(
    pool: &PgPool,
    user_id: Uuid,
    month: NaiveDate,
    generated_by: Option<Uuid>,
) -> Result<MonthlyReport, AppError> {
    let month = month_key(month);
    let from = month;
    let to = month_end(month);

    let attendance_days = attendance::list_range(pool, user_id, from, to).await?;
    let reports = analysis_reports::list_for_range(pool, user_id, from, to).await?;
    let grace_seconds = time_grants::sum_for_range(pool, user_id, from, to).await?;
    let threshold = alignment_threshold();

    // Index the day's analysis so the series can carry its score.
    let mut by_day = std::collections::HashMap::new();
    for r in &reports {
        by_day.insert(r.day, r);
    }

    let mut out = MonthlyReportInput {
        user_id,
        month,
        worked_seconds: 0,
        grace_seconds,
        days_present: 0,
        days_partial: 0,
        days_absent: 0,
        days_leave: 0,
        days_holiday: 0,
        days_weekend: 0,
        days_analyzed: 0,
        days_above_threshold: 0,
        alignment_threshold: threshold,
        avg_alignment_score: None,
        screenshots_analyzed: 0,
        days: Vec::new(),
        generated_by,
    };

    let mut score_sum = 0.0;
    for d in &attendance_days {
        out.worked_seconds += i64::from(d.worked_seconds);
        match d.status.as_str() {
            "present" => out.days_present += 1,
            "partial" => out.days_partial += 1,
            "absent" => out.days_absent += 1,
            "leave" => out.days_leave += 1,
            "holiday" => out.days_holiday += 1,
            "weekend" => out.days_weekend += 1,
            _ => {}
        }
        let report = by_day.get(&d.day);
        if let Some(r) = report {
            out.days_analyzed += 1;
            out.screenshots_analyzed += r.total_analyzed;
            score_sum += r.alignment_score;
            if r.alignment_score >= threshold {
                out.days_above_threshold += 1;
            }
        }
        out.days.push(MonthDay {
            day: d.day,
            worked_seconds: d.worked_seconds,
            status: d.status.clone(),
            alignment_score: report.map(|r| r.alignment_score),
            total_analyzed: report.map(|r| r.total_analyzed).unwrap_or(0),
        });
    }

    // A day can carry an analysis without an attendance row (rare: the rollup
    // hasn't run for that day yet). Count it so "days analysed" never under-reports.
    for r in &reports {
        if !attendance_days.iter().any(|d| d.day == r.day) {
            out.days_analyzed += 1;
            out.screenshots_analyzed += r.total_analyzed;
            score_sum += r.alignment_score;
            if r.alignment_score >= threshold {
                out.days_above_threshold += 1;
            }
            out.days.push(MonthDay {
                day: r.day,
                worked_seconds: 0,
                status: String::new(),
                alignment_score: Some(r.alignment_score),
                total_analyzed: r.total_analyzed,
            });
        }
    }
    out.days.sort_by_key(|d| d.day);

    if out.days_analyzed > 0 {
        out.avg_alignment_score = Some(score_sum / f64::from(out.days_analyzed));
    }

    monthly_reports::upsert(pool, out).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn month_key_normalises_any_day_to_the_first() {
        let d = NaiveDate::from_ymd_opt(2026, 8, 27).unwrap();
        assert_eq!(month_key(d), NaiveDate::from_ymd_opt(2026, 8, 1).unwrap());
    }

    #[test]
    fn month_end_handles_lengths_and_year_rollover() {
        let feb = NaiveDate::from_ymd_opt(2026, 2, 1).unwrap();
        assert_eq!(
            month_end(feb),
            NaiveDate::from_ymd_opt(2026, 2, 28).unwrap()
        );
        // 2028 is a leap year.
        let feb_leap = NaiveDate::from_ymd_opt(2028, 2, 1).unwrap();
        assert_eq!(
            month_end(feb_leap),
            NaiveDate::from_ymd_opt(2028, 2, 29).unwrap()
        );
        let dec = NaiveDate::from_ymd_opt(2026, 12, 1).unwrap();
        assert_eq!(
            month_end(dec),
            NaiveDate::from_ymd_opt(2026, 12, 31).unwrap()
        );
        let apr = NaiveDate::from_ymd_opt(2026, 4, 1).unwrap();
        assert_eq!(
            month_end(apr),
            NaiveDate::from_ymd_opt(2026, 4, 30).unwrap()
        );
    }

    #[test]
    fn threshold_defaults_to_fifty_percent() {
        // The env var is process-global; assert the default constant instead of
        // mutating it under parallel tests.
        assert_eq!(DEFAULT_ALIGNMENT_THRESHOLD, 50.0);
    }
}
